// Minislicer — vereinfachter Kontur-Slicer (Phase-0-Vorstufe zu libslic3r).
//
// Schneidet das Dreiecksnetz in Ebenen, verkettet die Schnittsegmente zu
// Konturen und erzeugt G-Code (nur Aussenwände, 1 Perimeter — kein Infill,
// keine Supports). Ehrlich als Vorschau-Qualität gekennzeichnet; in Phase 1
// übernimmt libslic3r aus BambuStudio das vollwertige Slicing.

#pragma once

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <string>
#include <unordered_map>
#include <vector>

namespace minislicer {

struct SliceParams {
    double layer_height = 0.2;   // mm
    double line_width = 0.42;    // mm
    double speed = 60.0;         // mm/s Druckgeschwindigkeit
    double travel_speed = 150.0; // mm/s
    double nozzle_temp = 220.0;  // °C
    double bed_temp = 55.0;      // °C
};

namespace detail {

struct Pt {
    double x, y;
};

// Quantisierung für die Endpunkt-Verkettung (1 µm)
inline int64_t quant(double v) { return llround(v * 1000.0); }

struct KeyHash {
    size_t operator()(const std::pair<int64_t, int64_t>& k) const {
        return std::hash<int64_t>()(k.first * 73856093 ^ k.second * 19349663);
    }
};

struct Segment {
    Pt a, b;
    bool used = false;
};

// Schnittpunkt einer Kante mit der Ebene z=zc
inline Pt edgeCut(const float* p, const float* q, double zc) {
    const double t = (zc - p[2]) / (double(q[2]) - p[2]);
    return {p[0] + t * (double(q[0]) - p[0]), p[1] + t * (double(q[1]) - p[1])};
}

// Alle Schnittsegmente der Ebene z=zc mit dem Netz
inline std::vector<Segment> layerSegments(const std::vector<float>& v, double zc) {
    std::vector<Segment> segs;
    const size_t nTri = v.size() / 9;
    for (size_t t = 0; t < nTri; ++t) {
        const float* a = &v[t * 9];
        const float* b = a + 3;
        const float* c = a + 6;
        Pt pts[3];
        int n = 0;
        const float* e[3][2] = {{a, b}, {b, c}, {c, a}};
        for (auto& ed : e) {
            const double z0 = ed[0][2], z1 = ed[1][2];
            if ((z0 < zc && z1 >= zc) || (z1 < zc && z0 >= zc)) {
                if (n < 3) pts[n++] = edgeCut(ed[0], ed[1], zc);
            }
        }
        if (n == 2) segs.push_back({pts[0], pts[1]});
    }
    return segs;
}

// Segmente zu Polylinien/Konturen verketten
inline std::vector<std::vector<Pt>> chainSegments(std::vector<Segment>& segs) {
    std::unordered_map<std::pair<int64_t, int64_t>, std::vector<size_t>, KeyHash> byStart;
    for (size_t i = 0; i < segs.size(); ++i) {
        byStart[{quant(segs[i].a.x), quant(segs[i].a.y)}].push_back(i);
        byStart[{quant(segs[i].b.x), quant(segs[i].b.y)}].push_back(i);
    }
    std::vector<std::vector<Pt>> polys;
    for (size_t i = 0; i < segs.size(); ++i) {
        if (segs[i].used) continue;
        segs[i].used = true;
        std::vector<Pt> poly = {segs[i].a, segs[i].b};
        // vorwärts verlängern, bis nichts mehr passt
        for (;;) {
            const Pt& tail = poly.back();
            auto it = byStart.find({quant(tail.x), quant(tail.y)});
            if (it == byStart.end()) break;
            bool extended = false;
            for (size_t j : it->second) {
                if (segs[j].used) continue;
                const bool fwd = quant(segs[j].a.x) == quant(tail.x) &&
                                 quant(segs[j].a.y) == quant(tail.y);
                segs[j].used = true;
                poly.push_back(fwd ? segs[j].b : segs[j].a);
                extended = true;
                break;
            }
            if (!extended) break;
        }
        if (poly.size() >= 3) polys.push_back(std::move(poly));
    }
    return polys;
}

}  // namespace detail

// Sliced das Netz (Dreiecks-Suppe, mm) und liefert kompletten G-Code.
inline std::string sliceToGcode(const std::vector<float>& verts, const SliceParams& p) {
    using namespace detail;

    double zmin = 1e30, zmax = -1e30;
    for (size_t i = 2; i < verts.size(); i += 3) {
        zmin = std::min(zmin, double(verts[i]));
        zmax = std::max(zmax, double(verts[i]));
    }
    if (verts.empty() || zmax <= zmin) return "; Minislicer: leeres Modell\n";

    const double h = p.layer_height;
    const int nLayers = std::max(1, int(std::floor((zmax - zmin) / h)));

    // E pro mm Weg: Spurquerschnitt / Filamentquerschnitt (1,75-mm-Filament)
    const double filament_area = M_PI * 0.875 * 0.875;
    const double e_per_mm = (h * p.line_width) / filament_area;

    std::string g;
    g.reserve(1 << 20);
    char buf[160];
    auto emit = [&](const char* fmt, auto... args) {
        std::snprintf(buf, sizeof(buf), fmt, args...);
        g += buf;
    };

    double extrudeDist = 0, travelDist = 0;

    g += "; generated by Minislicer (vereinfachter Kontur-Slicer)\n";
    g += "; WARNUNG: nur Aussenkonturen, 1 Wand, kein Infill/Support — Vorschau-Qualitaet\n";
    emit("; layer_height = %.2f\n; line_width = %.2f\n", h, p.line_width);
    emit("M104 S%.0f\nM140 S%.0f\nG28\nM190 S%.0f\nM109 S%.0f\n",
         p.nozzle_temp, p.bed_temp, p.bed_temp, p.nozzle_temp);
    g += "G90\nM83\nG92 E0\nM106 S255\n";

    double lastX = 0, lastY = 0;
    for (int layer = 0; layer < nLayers; ++layer) {
        const double zc = zmin + (layer + 0.5) * h;
        const double printZ = zmin + (layer + 1) * h;
        auto segs = layerSegments(verts, zc);
        auto polys = chainSegments(segs);
        emit(";LAYER:%d\nG1 Z%.3f F600\n", layer, printZ);
        for (const auto& poly : polys) {
            emit("G0 X%.3f Y%.3f F%.0f\n", poly[0].x, poly[0].y, p.travel_speed * 60);
            travelDist += std::hypot(poly[0].x - lastX, poly[0].y - lastY);
            for (size_t i = 1; i < poly.size(); ++i) {
                const double d = std::hypot(poly[i].x - poly[i - 1].x,
                                            poly[i].y - poly[i - 1].y);
                if (d < 1e-6) continue;
                extrudeDist += d;
                emit("G1 X%.3f Y%.3f E%.5f F%.0f\n", poly[i].x, poly[i].y,
                     d * e_per_mm, p.speed * 60);
            }
            lastX = poly.back().x;
            lastY = poly.back().y;
        }
    }

    g += "M107\nM104 S0\nM140 S0\nG91\nG1 Z5 F600\nG90\nM84\n";

    const double timeSec = extrudeDist / p.speed + travelDist / p.travel_speed + nLayers * 0.3;
    const double filamentMm = extrudeDist * e_per_mm;
    emit("; minislicer_layers = %d\n", nLayers);
    emit("; minislicer_time_s = %.0f\n", timeSec);
    emit("; minislicer_filament_mm = %.1f\n", filamentMm);
    return g;
}

}  // namespace minislicer
